name: notify

on:
  workflow_run:
    workflows:
      - "*"
    types:
      - completed

jobs:
  notify:
    name: Notify on workflow failure
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.workflow_run.url }}
      - run: echo ${{ github.event.workflow_run.name }}
      - run: echo ${{ github.event.workflow_run.requested_action }}
      - run: echo ${{ github.event.workflow_run.sender }}
