name: notify

on:
  push

jobs:
  notify:
    name: Notify on workflow failure
    runs-on: ubuntu-latest
    steps:
      - name: Test
        id: test
        run: |
          healthcheckHost=$(echo "\"test\"" | sed 's/\"//g')
          echo "::set-output name=HEALTHCHECK_HOST::$healthcheckHost"
      - run: echo ${{ steps.test.outputs.HEALTHCHECK_HOST }}
