name: notify

on:
  workflow_run:
    workflows:
      - "*"
    types:
      - completed

jobs:
  notify:
    name: Notify on workflow failure
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.workflow_run.details_url }}
      - run: echo ${{ github.event.workflow_run.head_sha }}
      - run: echo ${{ github.event.workflow_run.node_id }}
      - run: echo ${{ github.event.workflow_run.head_branch }}
      - run: echo ${{ github.event.workflow_run.details_url }}
      - run: echo ${{ github.event.workflow_run.details_url }}
      - run: echo ${{ github.event.workflow_run.details_url }}
      - run: echo ${{ github.event.workflow_run.details_url }}
