name: testagain

on:
  push

jobs:
  package:
    name: Build, test and lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Exit 1
        run: exit 1
